# Generated by Django 5.2 on 2025-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_book_image_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
