# Generated by Django 5.1.6 on 2025-12-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
        ),
    ]
